apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: petclinic-app-mysql
spec:
  storageClassName: rbd-storagepool-cluster
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce