apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic-app-mysql
    app.kubernetes.io/part-of: pet-clinic
  name: petclinic-app-mysql
spec:
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: petclinic-app-mysql
  sessionAffinity: None
  type: ClusterIP
--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic-app-frontend
    app.kubernetes.io/part-of: pet-clinic
  name: petclinic-app-frontend
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: petclinic-app-frontend
  sessionAffinity: None
  type: ClusterIP
--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic-app-phpmyadmin
    app.kubernetes.io/part-of: pet-clinic
  name: petclinic-app-phpmyadmin
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: petclinic-app-adminer
  sessionAffinity: None
  type: ClusterIP
  